source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.7'
# Use postgresql as the database for Active Record
# gem 'pg', '~> 0.18'
gem 'pg', '~> 0.18.4'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'rack-attack'
gem 'devise_token_auth', "~>1.0.0"
gem 'omniauth'
gem 'active_model_serializers', '~> 0.10.0'
gem 'redis-rails'
# gem 'sidekiq'
gem 'delayed_job_active_record'
gem "daemons"
gem 'whenever', require: false
gem 'pdf-reader'
gem 'figaro'
gem 'closure_tree'
gem 'cancancan'
gem 'rolify'
gem "paperclip", '~>5.1.0'
gem 'paperclip-meta'
gem 'aws-sdk'
gem 'sendgrid-ruby'
gem 'shoulda'
#pagination
gem 'kaminari'
#faker for fake details
gem 'faker'
# #fabrication to fabricate details
# gem 'fabrication'
# For excel file import
gem 'roo'
gem 'creek'
# gem 'roo-xls'
gem 'rubyzip', '>= 1.2.1'
gem 'axlsx', git: 'https://github.com/randym/axlsx.git', ref: 'c8ac844'
gem 'axlsx_rails'
#ruby-units for measurements
gem 'ruby-units'
gem 'paper_trail'
gem 'swagger-docs'
#exception notifications
gem 'exception_notification'
gem 'plivo'
gem "rest-client"
gem "json"
gem "htmlentities"
# gem 'google-api-client', '~> 0.11'
gem 'bazaar'
gem 'newrelic_rpm'
gem 'prawn'
gem 'prawn-table'
gem 'fast_jsonapi'
gem 'numbers_and_words', '~> 0.10.5'
gem 'money'
gem 'active_model_otp'
gem 'rotp', '~>3.3.1'

# gems for handling mobile app push notifications
gem 'google-cloud-firestore'
gem 'rpush'

group :development, :fe_dev, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '>= 3.5.0'
  gem 'factory_girl_rails'
  gem 'rails-erd', require: false, group: :development
end
gem 'rswag'
# gem 'swagger-docs'

group :development, :fe_dev do
  gem 'listen', '~> 3.0.5'
  gem 'bullet'

  #to annotate the active record models
  gem 'annotate'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano'
  gem 'capistrano3-puma'
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rvm'
  gem 'rb-readline'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'rack-reverse-proxy', require: 'rack/reverse_proxy'
gem 'api-pagination'
gem 'deep_cloneable', '~> 2.3.2'
gem 'metainspector'
gem 'find_with_order'

gem 'indianize'
